#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2022 QuickVM, LLC <contact@quickvm.com> All Rights Reserved.

set -e

[[ $UID == 0 ]] || { echo "Please run this as root!"; exit 1; }

: ${UNIT_FILES:=./units}
: ${UNIT_DIR:=/etc/systemd/system}

[[ -d ${UNIT_FILES} ]] || { echo "The ${UNIT_FILES} directory cannot be found! Please run this from the repo root directory!"; exit 1; }

for FILE in ${UNIT_FILES}/*; do
  install -m 0644 ${FILE} ${UNIT_DIR}
  DEST="$(basename -- $FILE)"
  echo "Copied ${FILE} to ${UNIT_DIR}/${DEST}"
done

systemctl daemon-reload

echo ""
echo "Great job! The restic systemd units are now installed!"
echo ""
echo "If you want to uninstall these Restic systemd units please manually run these commands as the root user:"
echo "systemctl disable restic@local.service (do this for every backup repository)"
for FILE in ${UNIT_FILES}/*; do
  install -m 0644 ${FILE} ${UNIT_DIR}
  DEST="$(basename -- $FILE)"
  echo "rm -f ${UNIT_DIR}/${DEST}"
done
echo "systemctl daemon-reload"
